version: "3"
services:
  openai_signup_tool:
    image: ghcr.io/magicalmadoka/openai-signup-tool:latest
    #image: openai-signup
    container_name: openai-signup-tool
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
